kind: Service
apiVersion: v1
metadata:
  name: mongo-express-service
  labels:
    app: mongo-express-service
spec:
  selector:
    app: mongoexpresspod
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30000